steps:
  - label: ":hammer: Build"
    key: build
    artifact_paths:
      - ".gradle/**"
      - "**/build/**"
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
    command: |
      ./gradlew clean assemble --no-daemon

  - label: ":test_tube: Test"
    depends_on: build
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
          mount-buildkite-agent: true
    command: |
      buildkite-agent artifact download ".gradle/**" .
      buildkite-agent artifact download "**/build/**" .
      # run tests (Gradle should find compiled classes and avoid recompiling)
      ./gradlew test --no-daemon
