steps:
  - label: ":hammer: Build"
    key: build
    command: |
      ./gradlew clean assemble --no-daemon
    artifact_paths:
      - ".gradle/**"
      - "**/build/**"
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true

  - label: ":test_tube: Test"
    depends_on: build
    command: |
      # pull artifacts produced by the build step into the workspace
      buildkite-agent artifact download ".gradle/**" .
      buildkite-agent artifact download "**/build/**" .

      # run tests (Gradle should find compiled classes and avoid recompiling)
      ./gradlew test --no-daemon
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true