steps:
  - label: ":hammer: Build"
    key: build
    artifact_paths:
      - ".gradle/**"
      - "**/build/**"
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
    command: |
      ./gradlew clean assemble --no-daemon

  - label: ":test_tube: Test"
    depends_on: build
    plugins:
      # Download artifacts into the job’s working dir (host), before running the container
      - artifacts#v1.9.0:
          download:
            - ".gradle/**"
            - "**/build/**"
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
    command: |
      # run tests (Gradle should find compiled classes and avoid recompiling)
      ./gradlew test --no-daemon
