steps:
  - label: ":hammer: Build"
    key: build
    artifact_paths:
      - ".gradle/**"
      - "build/**"
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
    command: |
      ./gradlew clean assemble --no-daemon

  - label: ":test_tube: Test (with artifacts from cli)"
    depends_on: build
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
          mount-buildkite-agent: true
    command: |
      buildkite-agent artifact download ".gradle/**" .
      buildkite-agent artifact download "build/**" .
      # run tests (Gradle should find compiled classes and avoid recompiling)
      ./gradlew test --no-daemon

  - label: ":test_tube: Test (with artifacts from plugin)"
    depends_on: build
    plugins:
      # Download artifacts into the job’s working dir (host), before running the container
      - artifacts#v1.9.0:
          download:
            - ".gradle/**"
            - "build/**"
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
          mount-buildkite-agent: true
    command: |
      # run tests (Gradle should find compiled classes and avoid recompiling)
      ./gradlew test --no-daemon

  - label: ":test_tube: Test (no artifacts)"
    depends_on: build
    artifact_paths:
      - "build/test-results/test/TEST-*.xml"
    plugins:
      - docker#v5.9.0:
          image: eclipse-temurin:17-jdk
          always-pull: true
      - junit-annotate#v2.7.0:
          input: "build/test-results/test/TEST-*.xml"
    command: |
      ./gradlew test --no-daemon
