steps:
  - label: ":hammer: Build"
    key: build
    artifact_paths:
      - "bazel-bin/**"
    plugins:
      - docker#v5.9.0:
          image: gcr.io/bazel-public/bazel:latest
          always-pull: true
    command: |
      bazel build //:spring-hello

  - label: ":test_tube: Test"
    depends_on: build
    plugins:
      - docker#v5.9.0:
          image: gcr.io/bazel-public/bazel:latest
          always-pull: true
    command: |
      bazel test //... --test_output=errors
    artifact_paths:
      - "bazel-testlogs/**/test.log"
      - "bazel-testlogs/**/test.xml"

  - wait: ~
    continue_on_failure: true

  - label: ":memo: JUnit annotate"
    plugins:
      - junit-annotate#v2.7.0:
          artifacts: "bazel-testlogs/**/test.xml"
